import { InfographicPage } from '../types';
import { ArrowLeft, Download } from 'lucide-react';

interface InfographicViewProps {
  data: InfographicPage;
  onBack: () => void;
}

export function InfographicView({ data, onBack }: InfographicViewProps) {
  return (
    <div className="min-h-screen bg-slate-100 p-8 font-sans">
      <div className="max-w-4xl mx-auto">
        <div className="mb-6 flex items-center justify-between print:hidden">
          <button
            onClick={onBack}
            className="flex items-center text-slate-600 hover:text-slate-900 font-medium transition-colors"
          >
            <ArrowLeft className="w-4 h-4 mr-2" /> Back to results
          </button>
          <button
            onClick={() => window.print()}
            className="flex items-center px-4 py-2 bg-white border border-slate-300 rounded-md shadow-sm text-slate-700 hover:bg-slate-50 font-medium transition-colors"
          >
            <Download className="w-4 h-4 mr-2" /> Print / Save PDF
          </button>
        </div>

        <div className="bg-white shadow-xl rounded-xl overflow-hidden print:shadow-none">
          {/* Header */}
          <div className="bg-zerpha-900 text-white p-10">
            <h1 className="text-4xl font-bold mb-3 tracking-tight">{data.title}</h1>
            <p className="text-zerpha-100 text-xl font-light leading-relaxed">{data.subtitle}</p>
          </div>

          <div className="p-10 space-y-10">
            {/* Key Metrics Grid */}
            <section>
              <h2 className="text-sm font-bold text-slate-400 uppercase tracking-wider mb-6">Key Metrics</h2>
              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
                {data.key_metrics.map((metric, idx) => (
                  <div key={idx} className="p-6 bg-slate-50 rounded-xl border border-slate-100 shadow-sm hover:shadow-md transition-shadow">
                    <dt className="text-sm font-medium text-slate-500 mb-1">{metric.label}</dt>
                    <dd className="text-2xl font-bold text-slate-900">{metric.value}</dd>
                  </div>
                ))}
              </div>
            </section>

            {/* Strategic Analysis Bullets */}
            <section>
              <h2 className="text-sm font-bold text-slate-400 uppercase tracking-wider mb-6">Strategic Analysis</h2>
              <ul className="space-y-4">
                {data.bullets.map((bullet, idx) => (
                  <li key={idx} className="flex items-start">
                    <span className="flex-shrink-0 w-1.5 h-1.5 rounded-full bg-zerpha-500 mt-2.5 mr-4" />
                    <span className="text-lg text-slate-700 leading-relaxed">{bullet}</span>
                  </li>
                ))}
              </ul>
            </section>
          </div>

          {/* Footer */}
          <div className="bg-slate-50 px-10 py-6 border-t border-slate-100 flex justify-between items-center text-xs text-slate-400">
            <span>Generated by Zerpha AI</span>
            <span>Confidential - Internal Use Only</span>
          </div>
        </div>
      </div>
    </div>
  );
}




